"""empty message

Revision ID: 2f28c8d0da81
Revises: e90c2616be56
Create Date: 2017-03-17 12:45:02.514471

"""

# revision identifiers, used by Alembic.
revision = '2f28c8d0da81'
down_revision = 'e90c2616be56'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quiz_answer', sa.Column('correct', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quiz_answer', 'correct')
    ### end Alembic commands ###
