"""empty message

Revision ID: 3ee57eab17f7
Revises: 59850a9429e1
Create Date: 2016-10-13 15:37:18.412803

"""

# revision identifiers, used by Alembic.
revision = '3ee57eab17f7'
down_revision = '59850a9429e1'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('username', sa.String(length=120), nullable=True))
    op.create_unique_constraint(None, 'user', ['username'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'username')
    ### end Alembic commands ###
