"""empty message

Revision ID: 4c819eee295c
Revises: dafeb3b4ccb2
Create Date: 2016-10-21 10:38:34.687224

"""

# revision identifiers, used by Alembic.
revision = '4c819eee295c'
down_revision = 'dafeb3b4ccb2'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('permission', sa.Column('description', sa.String(length=240), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('permission', 'description')
    ### end Alembic commands ###
