"""empty message

Revision ID: 61bd7d4f3c25
Revises: f511bb5344b7
Create Date: 2016-11-03 11:58:17.047574

"""

# revision identifiers, used by Alembic.
revision = '61bd7d4f3c25'
down_revision = 'f511bb5344b7'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lesson', sa.Column('school_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'lesson', 'school', ['school_id'], ['id'])
    op.add_column('subject', sa.Column('school_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'subject', 'school', ['school_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'subject', type_='foreignkey')
    op.drop_column('subject', 'school_id')
    op.drop_constraint(None, 'lesson', type_='foreignkey')
    op.drop_column('lesson', 'school_id')
    ### end Alembic commands ###
