"""empty message

Revision ID: 8bd0777b8a6c
Revises: ca52c2b966ba
Create Date: 2016-10-18 19:22:30.481695

"""

# revision identifiers, used by Alembic.
revision = '8bd0777b8a6c'
down_revision = 'ca52c2b966ba'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('school_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user', 'school', ['school_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'school_id')
    ### end Alembic commands ###
