"""empty message

Revision ID: 90cb77fa8e4e
Revises: 8bd0777b8a6c
Create Date: 2016-10-18 19:32:45.100597

"""

# revision identifiers, used by Alembic.
revision = '90cb77fa8e4e'
down_revision = '8bd0777b8a6c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_username_key', 'user', type_='unique')
    op.create_unique_constraint(None, 'user', ['school_id', 'username'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.create_unique_constraint('user_username_key', 'user', ['username'])
    ### end Alembic commands ###
