"""empty message

Revision ID: ca52c2b966ba
Revises: 3ee57eab17f7
Create Date: 2016-10-18 19:01:36.562706

"""

# revision identifiers, used by Alembic.
revision = 'ca52c2b966ba'
down_revision = '3ee57eab17f7'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('school',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('school')
    ### end Alembic commands ###
