"""empty message

Revision ID: e90c2616be56
Revises: 9db2b8105fd8
Create Date: 2017-03-15 15:05:52.413161

"""

# revision identifiers, used by Alembic.
revision = 'e90c2616be56'
down_revision = '9db2b8105fd8'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'comment', 'user', ['user_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'comment', type_='foreignkey')
    op.drop_column('comment', 'user_id')
    ### end Alembic commands ###
